### ISSUE TITLE
没有加载中文字幕

### ISSUE THREAD

**Issue by taocwang** [daineseh/kodi-plugin.video.ted-talks-chinese#1]
您好，今天下载了kodi-plugin.video.ted-talks-chinese使用，各方面都正常，但是没有加载中文字幕。请问是本身就不加载中文字幕还是我哪儿设置有问题呢，谢谢。

**Comment by daineseh** [comment]
Hi taocwang, 
Plugin 裡提供的影片都是有中文字幕的 Talk，但有發現偶爾不加載中文字幕的情況，但重新播放一次影片後就會正常。如果可以的話，請告訴我當字幕不加載時，重新播放一次 talk 看是否能夠成功載入字幕，謝謝。

目前還不知道重現問題的方法，懷疑是程式已將字幕已備妥，而影片串流還沒有準備好，開啟字幕功能比串流播放提早開啟導致字幕功能失效。

**Comment by taocwang** [comment]
真的是这样，重新播放一次字幕載入成功，谢谢！

**Comment by daineseh** [comment]
不客氣。
